#!/bin/bash

set -o allexport
source secret/env-prod
set +o allexport

PROJECT_DIR=$(pwd)

reset_supervisor=false
reset_nginx=false

while getopts 'is' flag; do
	case "${flag}" in
		s) reset_supervisor=true ;;
		i) reset_nginx=true ;;
	esac
done

# supervisor setup

if [ "$reset_supervisor" = true ]; then
	cp 'config/supervisor/hive-for-mobile-server.conf' $SUPERVISOR_CONF_DEST
	sed -i '' "s/\$USER/$USER/g" $SUPERVISOR_CONF_DEST
	sed -i '' "s/\$PROJECT_DIR/$PROJECT_DIR/g" $SUPERVISOR_CONF_DEST
	sed -i '' "s/\$PROJECT_PORT/$PROJECT_PORT/g" $SUPERVISOR_CONF_DEST
	supervisorctl reread
	supervisorctl add 'hive-for-mobile-server'
fi

supervisorctl start 'hive-for-mobile-server'

# nginx setup

if [ "$reset_nginx" = true ]; then
	cp 'config/nginx/hive-for-mobile-server.production.conf' $NGINX_CONF_DEST
	sed -i '' "s~\$PROJECT_DIR~$PROJECT_DIR~g" $NGINX_CONF_DEST
	sed -i '' "s/\$PROJECT_HOST/$PROJECT_HOST/g" $NGINX_CONF_DEST
	sed -i '' "s/\$PROJECT_PORT/$PROJECT_PORT/g" $NGINX_CONF_DEST
	sed -i '' "s~\$SSL_CERT_LOCATION~$SSL_CERT_LOCATION~g" $NGINX_CONF_DEST
	sed -i '' "s~\$SSL_CERT_KEY_LOCATION~$SSL_CERT_KEY_LOCATION~g" $NGINX_CONF_DEST

	if [[ -z "$NGINX_CONF_LINK" ]]; then
		ln -s $NGINX_CONF_DEST $NGINX_CONF_LINK
	fi

	sudo service nginx restart
fi

sudo service nginx start
